apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bjj-coach
  namespace: "bjjcoach-454315"
  annotations:
    run.googleapis.com/launch-stage: ALPHA
    run.googleapis.com/startup-cpu-boost: 'true'
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      serviceAccountName: 781030252850-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/781030252850/bjj-coach
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: YOUTUBE_API_KEY
          valueFrom:
            secretKeyRef:
              name: youtube-api-key
              key: latest
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: latest
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-host
              key: latest
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-port
              key: latest
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-name
              key: latest
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-user
              key: latest
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: latest
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 30
          failureThreshold: 3

