apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bjj-coach
  namespace: "781030252850"
  annotations:
    run.googleapis.com/launch-stage: ALPHA
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/health-check-disabled: 'true'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containers:
      - image: gcr.io/781030252850/bjj-coach
        command:
        - sh
        - -c
        - |
          # Copy files to a writable directory
          cp -r /workspace/* /tmp/
          cd /tmp
          
          # Install dependencies with specific flags
          npm install --production --no-package-lock --no-audit
          
          # Start the application
          node src/index.js
        env:
        - name: NODE_ENV
          value: "production"
        - name: YOUTUBE_API_KEY
          value: ${YOUTUBE_API_KEY}
        - name: JWT_SECRET
          value: ${JWT_SECRET}
        - name: DB_HOST
          value: ${DB_HOST}
        - name: DB_PORT
          value: ${DB_PORT}
        - name: DB_NAME
          value: ${DB_NAME}
        - name: DB_USER
          value: ${DB_USER}
        - name: DB_PASSWORD
          value: ${DB_PASSWORD}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: cloud-storage
          mountPath: /workspace/public
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 3
          failureThreshold: 1
      volumes:
      - name: cloud-storage
        gcs:
          bucketName: bjjcoach-files
          readOnly: false

