apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bjj-coach
  namespace: "bjjcoach-454315"
  annotations:
    run.googleapis.com/launch-stage: ALPHA
    run.googleapis.com/startup-cpu-boost: 'true'
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containers:
      - image: gcr.io/bjjcoach-454315/bjj-coach
        args:
        - node
        - src/index.js
        env:
        - name: NODE_ENV
          value: "production"
        - name: YOUTUBE_API_KEY
          value: $(YOUTUBE_API_KEY)
        - name: JWT_SECRET
          value: $(JWT_SECRET)
        - name: DB_HOST
          value: $(DB_HOST)
        - name: DB_PORT
          value: $(DB_PORT)
        - name: DB_NAME
          value: $(DB_NAME)
        - name: DB_USER
          value: $(DB_USER)
        - name: DB_PASSWORD
          value: $(DB_PASSWORD)
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 3
          failureThreshold: 1

