apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bjj-coach
  annotations:
    run.googleapis.com/launch-stage: ALPHA
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/health-check-disabled: 'true'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containers:
      - image: gcr.io/bjj-coach-781030252850/bjj-coach
        command:
        - sh
        - -c
        - |
          # Copy files to a writable directory
          cp -r /workspace/* /tmp/
          cd /tmp
          
          # Install dependencies with specific flags
          npm install --production --no-package-lock --no-audit
          
          # Start the application
          node src/index.js
        env:
        - name: NODE_ENV
          value: "production"
        - name: YOUTUBE_API_KEY
          valueFrom:
            secretKeyRef:
              name: youtube-api-key
              key: latest
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: latest
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-host
              key: latest
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-port
              key: latest
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-name
              key: latest
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-user
              key: latest
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: gcs-mount
          mountPath: /workspace
          readOnly: true
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 3
          failureThreshold: 3
      volumes:
      - name: gcs-mount
        csi:
          driver: gcsfuse.run.googleapis.com
          readOnly: true
          volumeAttributes:
            bucketName: bjjcoach-files

