apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bjj-coach
  annotations:
    run.googleapis.com/launch-stage: ALPHA
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/health-check-disabled: 'true'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/serverless-runtimes/google-22/runtimes/nodejs22
        command:
        - sh
        - -c
        - |
          # Create a temporary directory for our application
          mkdir -p /app
          cd /app
          
          # Copy files from the read-only mount to our writable directory
          cp -r /workspace/* /app/
          
          # Install dependencies
          npm ci
          
          # Start the application
          node src/index.js
        env:
        - name: NODE_ENV
          value: "production"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        volumeMounts:
        - name: gcs-mount
          mountPath: /workspace
          readOnly: true
      volumes:
      - name: gcs-mount
        csi:
          driver: gcsfuse.run.googleapis.com
          readOnly: true
          volumeAttributes:
            bucketName: bjjcoach-files

