apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bjj-coach
  annotations:
    run.googleapis.com/launch-stage: ALPHA
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/health-check-disabled: 'true'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/serverless-runtimes/google-22/runtimes/nodejs22
        command:
        - sh
        - -c
        - |
          # Copy files to a writable directory
          cp -r /workspace/* /tmp/
          cd /tmp
          
          # Create a directory for npm
          mkdir -p /tmp/npm
          
          # Install dependencies with custom npm configuration
          npm config set cache /tmp/npm --global
          npm ci --no-cache
          
          # Start the application
          node src/index.js
        env:
        - name: NODE_ENV
          value: "production"
        - name: HOME
          value: "/tmp"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        volumeMounts:
        - name: gcs-mount
          mountPath: /workspace
          readOnly: true
      volumes:
      - name: gcs-mount
        csi:
          driver: gcsfuse.run.googleapis.com
          readOnly: true
          volumeAttributes:
            bucketName: bjjcoach-files

