name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE_NAME: bjj-coach
  BUCKET_NAME: bjjcoach

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud config set run/region ${{ env.REGION }}

      - name: Copy files to Cloud Storage
        run: |
          gcloud storage cp -r ./* gs://${{ env.BUCKET_NAME }}/

      - name: Deploy to Cloud Run
        run: |
          gcloud run services replace cloud-run-instant-deploy-main/service.yaml
          gcloud run services update ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --update-env-vars DATE=$(date +%Y-%m-%d_%H:%M:%S)

      - name: Make service public
        run: |
          gcloud run services add-iam-policy-binding ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --member="allUsers" \
            --role="roles/run.invoker" 