name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: bjjcoach-454315
  REGION: us-central1
  SERVICE_NAME: bjjcoach
  BUCKET_NAME: bjjcoach-files

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Token Info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event Name: ${{ github.event_name }}"

      - uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          token_format: 'access_token'
          audience: 'sts.googleapis.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud config set run/region ${{ env.REGION }}

      - name: Copy files to Google Cloud Storage
        run: |
          gcloud storage cp -r ./* gs://${{ env.BUCKET_NAME }}/

      - name: Deploy to Cloud Run
        run: |
          gcloud run services replace cloud-run-instant-deploy-main/service.yaml
          gcloud run services update ${{ env.SERVICE_NAME }} \
            --region=${{ env.REGION }} \
            --update-env-vars=DATE=$(date +%Y-%m-%d_%H:%M:%S)

      - name: Make service public
        run: |
          gcloud run services add-iam-policy-binding ${{ env.SERVICE_NAME }} \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --region=${{ env.REGION }} 